### PR TITLE
update mockito as version 1 was complaining for reflection access and…

### PR DESCRIPTION
**Pull request by KroArtem**
… replace mockito deprecations

### CODE REVIEW

**Comment by KroArtem** [comment]
@eroshenkoam , ping

**Comment by eroshenkoam** [comment]
@KroArtem ty)
May be you can help me with GitHub Actions?
I'd like to migrate from jenkins

**Comment by eroshenkoam** [comment]
I setup it for allure-android, for example: 
https://github.com/allure-framework/allure-android

**Comment by KroArtem** [comment]
I'll try to have a look soon 👌

**Pull request merged**
